version: "3.9"
services:
  db:
    image: postgres:14
    container_name: 'db-booking-hotel'
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
